spring:
  application:
    name: user-service
  cloud:
    # 限流：在 Sentinel 控制台按资源名配置流控规则（authLogin / userCreate / userGet）
    sentinel:
      transport:
        dashboard: 127.0.0.1:8090
      eager: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        fail-fast: false
        namespace: e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      config:
        server-addr: 127.0.0.1:8848
        fail-fast: false
        import-check:
          enabled: false
        namespace: e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      username: nacos
      password: Wzq20030828
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:user-service-dev.yaml?group=DEFAULT_GROUP&namespace=e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      - optional:nacos:user-db.yaml?group=DEFAULT_GROUP&namespace=e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      - optional:nacos:management.yaml?group=DEFAULT_GROUP&namespace=e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      - optional:nacos:jwt.yaml?group=DEFAULT_GROUP&namespace=e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
server:
  port: 8081
