spring:
  application:
    name: book-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        fail-fast: false
        namespace: e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      config:
        server-addr: 127.0.0.1:8848
        fail-fast: false
        import-check:
          enabled: false
        namespace: e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      username: nacos
      password: Wzq20030828
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:book-service-dev.yaml?group=DEFAULT_GROUP&namespace=e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      - optional:nacos:book-db.yaml?group=DEFAULT_GROUP&namespace=e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
      - optional:nacos:management.yaml?group=DEFAULT_GROUP&namespace=e85adfe2-9c4d-43f6-b4d5-ae811f5d41f2
server:
  port: 8082